---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: focalboard
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: focalboard
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
      PORT: 8000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: 75M
        hosts:
          - host: boards.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - boards.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
