apiVersion: apps/v1
kind: Deployment
metadata:
  name: gminer-rvn
  namespace: tools
spec:
  replicas: 5
  selector:
    matchLabels:
      run: gminer-rvn
  template:
    metadata:
      labels:
        run: gminer-rvn
    spec:
      tolerations:
        - key: "workstation"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: gminer-rvn
          image: "dockminer/gminer:latest"
          #image: "registry.imake.software/sparks/gminer-rvn:v3.1.0"
          imagePullPolicy: Always
          env:
            - name: DISPLAY
              value: :0
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: 100m
              memory: "1024Mi"
          args:
            - --algo
            - kawpow
            - --server
            - rvn.2miners.com:6060
            - --user
            - "RD1C9QhqFpxCaXxBbybJzVjhG2Ab3m275e.$(POD_UID)"
            - -p
            - "x"
