---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns-internal
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: coredns
      version: 1.16.3
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    serviceType: "LoadBalancer"
    service:
      loadBalancerIP: 10.10.0.254
      annotations:
        metallb.universe.tf/allow-shared-ip: "DNS"
