apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-gitlab
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-gitlab
    spec:
      domain:
        resources:
          requests:
            memory: 4096M
        devices:
          disks:
            - name: gitlab-hdd
              disk:
                bus: virtio
      volumes:
        - name: gitlab-hdd
          persistentVolumeClaim:
            claimName: gitlab-hdd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-hdd
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
