---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app glauth
  namespace: auth
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    image:
      repository: docker.io/glauth/glauth
      tag: v2.1.0
    command: ["/app/glauth", "-c", "/config"]
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.10.201.7
        ports:
          http:
            port: 5555
          ldap:
            enabled: true
            port: 389
    persistence:
      config:
        enabled: true
        type: secret
        name: *app
        items:
          - key: server.toml
            path: server.toml
          - key: groups.toml
            path: groups.toml
          - key: users.toml
            path: users.toml
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 200Mi
