---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: networking-samba
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: America/Chicago
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.10.201.8
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 445
          netbios:
            enabled: true
            protocol: TCP
            port: 139
    persistence:
      share1:
        enabled: true
        existingClaim: pxe-sparks-codes-pvc
        accessMode: ReadWriteMany
        mountPath: /share/samba/pxe.sparks.codes
    configmap:
      config:
        # -- Store samba configuration as a ConfigMap
        enabled: true
        # -- Samba configuration. See [image documentation](https://github.com/crazy-max/docker-samba#configuration) for more information.
        # @default -- See values.yaml
        data:
          config.yml: |
            auth:
              - user: sparks
                group: sparks
                uid: 1000
                gid: 1000
                password: ${NETWORKING_SAMBA_SPARKS_PASSWORD}
            global:
              - "force user = sparks"
              - "force group = sparks"
            share:
              - name: pxe.sparks.codes
                path: /share/samba/pxe.sparks.codes
                browsable: yes
                readonly: no
                guestok: no
                validusers: sparks
                writelist: sparks
                veto: no
