---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: calico-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tigera-operator
      version: v3.20.0
      sourceRef:
        kind: HelmRepository
        name: projectcalico-charts
        namespace: flux-system
      interval: 5m
  values:
