---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/zigbee2mqtt.sparks.codes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: zigbee-controller
              operator: In
              values:
                - "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data-pvc
  namespace: home
spec:
  volumeName: zigbee2mqtt-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
