---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-cwh11
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 6144Mi
        cpu: 500m
    minecraftServer:
      eula: "TRUE"
      version: "1.17.1"
      type: SPIGOT
      motd: "testing.mc.sparks.codes"
      difficulty: normal
      ops: "superdigdug"
      maxPlayers: 20
      viewDistance: 14
      #levelSeed:
      gameMode: creative
      pvp: true
      onlineMode: false
      memory: 6144M
      serviceType: LoadBalancer
      loadBalancerIP: 10.11.2.2
    persistence:
      dataDir:
        enabled: true
    extraVolumes:
      - volumeMounts:
          - name: nfs
            mountPath: /data
            subPath: "mc.sparks.codes/cwh11"
        volumes:
          - name: nfs
            persistentVolumeClaim:
              claimName: nfs
