---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-cwh11
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 15m
  values:
    image: itzg/minecraft-server
    imageTag: latest
    nodeSelector:
      services/minecraft: active
    resources:
      requests:
        memory: 8192Mi
        cpu: 2000m
    minecraftServer:
      eula: "TRUE"
      version: "1.18.2"
      type: SPIGOT
      motd: "cwh11.mc.sparks.codes"
      difficulty: normal
      ops: "superdigdug"
      worldSaveName: world_cwh11
      maxPlayers: 20
      viewDistance: 14
      levelSeed: -6121001965162030037
      gameMode: survival
      pvp: true
      onlineMode: false
      memory: 8192M
      serviceType: LoadBalancer
      loadBalancerIP: 10.10.202.2
      rcon:
        enabled: true
        password: "minecraft2145"
    persistence:
      dataDir:
        enabled: true
        existingClaim: local-mc-cwh11

---
apiVersion: v1
kind: Service
metadata:
  name: cwh11-dynmap
  namespace: games
  labels:
    app: minecraft-cwh11-minecraft
spec:
  ports:
    - port: 80
      targetPort: 8123
      protocol: TCP
  selector:
    app: minecraft-cwh11-minecraft

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cwh11-dynmap
  namespace: games
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - host: dynmap-cwh11.mc.sparks.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cwh11-dynmap
                port:
                  number: 80
