apiVersion: apps/v1
kind: Deployment
metadata:
  name: gminer-eth-trevor
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gminer-eth-trevor
  template:
    metadata:
      labels:
        run: gminer-eth-trevor
    spec:
      affinity:
        nodeAffinity:
          k3s.io/hostname: kappa
      containers:
        - name: gminer-eth
          image: "dockminer/gminer:latest"
          #image: "registry.imake.software/sparks/gminer-eth:v3.1.0"
          env:
            - name: DISPLAY
              value: :0
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: 100m
              memory: "1024Mi"
          args:
            - --algo
            - ethash
            - --server
            # pool
            - us-eth.2miners.com:2020
            # solo
            #- solo-eth.2miners.com:6060
            - --user
            # BTC
            #- 39ZA8zqaNAn4JJU8KzjW9ya5p9rNcCGiCo.$(POD_UID)
            # ETH
            - "0xD4145bEFDDE842f3Cbc8ce1a1d1094fD6d242eFf.$(POD_UID)"
