apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: openebs-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/storage/openebs
  prune: true
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: openebs-volumes
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: openebs-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/storage/openebs/volumes
  prune: true
  validation: client
