kind: Service
apiVersion: v1
metadata:
  name: external-gitlab-imake-software
  namespace: gitlab
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gitlab.imake.software
spec:
  type: ExternalName
  externalName: imake.software

---
kind: Service
apiVersion: v1
metadata:
  name: external-registry-imake-software
  namespace: gitlab
  annotations:
    external-dns.alpha.kubernetes.io/hostname: registry.imake.software
spec:
  type: ExternalName
  externalName: imake.software
