---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app grafana
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 8.2.20
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    admin:
      user: admin
      password: "${TOOLS_GRAFANA_ADMIN_PASSWORD}"

    ingress:
      enabled: true
      hostname: grafana.sparks.codes
      ingressClassName: nginx-internal
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "Grafana"
        hajimari.io/icon: "monitor-dashboard"
      extraTls:
        - secretName: acme-crt-secret-sparks-codes
          hosts:
            - grafana.sparks.codes
    persistence:
      existingClaim: "grafana-pvc"
      size: 10Gi
