apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-gitlab
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-gitlab
        app: gitlab
    spec:
      domain:
        resources:
          requests:
            memory: 4096M
        devices:
          disks:
            - name: gitlab-hdd
              bootOrder: 1
              disk:
                bus: virtio
      volumes:
        - name: gitlab-hdd
          persistentVolumeClaim:
            claimName: gitlab-hdd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-hdd
spec:
  storageClassName: ceph-block
  resources:
    requests:
      storage: 120Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
