---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
  namespace: default
spec:
  selector:
    app: gitlab
  type: LoadBalancer
  loadBalancerIP: 10.11.0.5
  ports:
    - port: 22
      protocol: TCP
      targetPort: 22
    - port: 80
      protocol: TCP
      targetPort: 80
