---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
  namespace: default
spec:
  selector:
    app: gitlab
  ports:
    - port: 22
      protocol: TCP
      targetPort: 22

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-http
  namespace: default
spec:
  selector:
    app: gitlab
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-https
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - gitlab.imake.software
      secretName: acme-crt-secret-imake-software
  rules:
    - host: gitlab.imake.software
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gitlab-http
                port:
                  number: 80
