apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: certmanager-controller
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/cert-manager/chart
  prune: true
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: certmanager-cluster-issuers
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: certmanager-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/cert-manager/issuers
  prune: true
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: certmanager-certificates
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: certmanager-cluster-issuers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/cert-manager/certs
  prune: true
  validation: client
