---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sharry
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sharry
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Sharry"
          hajimari.io/icon: "text"
          nginx.ingress.kubernetes.io/client-body-buffer-size: "2048m"
          nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
        hosts:
          - host: share.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - share.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      config:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 200Gi
    config: |
      sharry.restserver {
        # base-url = "https://sharry.${DOMAIN}"
        bind {
          address = "0.0.0.0"
          port = {{ .Values.service.main.ports.http.port }}
        }
        backend {
          auth {
            fixed {
              enabled = false  # set to true to enable this auth provider
              user = "admin"
              password = "admin"
              order = 10
            }
          }
        }
      }
