---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
          nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          hajimari.io/enable: "true"
          hajimari.io/appName: "Books"
          hajimari.io/icon: "book"
        hosts:
          - host: "books.sparks.codes"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "books.sparks.codes"
            secretName: acme-crt-secret-sparks-codes
    persistence:
      config:
        enabled: true
        existingClaim: local-calibre-config
      books:
        enabled: true
        existingClaim: local-calibre-books
