---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      tag: 10.7.7
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Jellyfin"
          hajimari.io/icon: "play-network"
        hosts:
          - host: media.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - media.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: nfs-jellyfin-config
        subPath: media.sparks.codes/config
      media:
        enabled: true
        type: pvc
        existingClaim: nfs-jellyfin-media
        subPath: media.sparks.codes/media
        retain: true
    hostNetwork: true
    resources:
      limits:
        nvidia.com/gpu: 1
