---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 25Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/static/media.sparks.codes/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-jellyfin-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 25Gi
