---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellyfin-config
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 25Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: omega.sparks.codes
    path: "/mnt/static/media.sparks.codes/config"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-jellyfin-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 25Gi
