---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 14Ti
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/media-vault/media.sparks.codes/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - tango

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-jellyfin-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
