---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellyfin-media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Ti
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: omega.sparks.codes
    path: /mnt/static/media.sparks.codes/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-jellyfin-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
