---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://portainer.github.io/k8s
      chart: portainer
      version: 1.0.19
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 15m
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-internal
      hosts:
        - host: portainer.sparks.codes
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: acme-crt-secret-sparks-codes
          hosts:
            - portainer.sparks.codes
    persistence:
      storageClass: ceph-block
