---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  dependsOn:
    - name: mosquitto
      namespace: home
    - name: zigbee2mqtt
      namespace: home
  values:
    env:
      TZ: "America/Chicago"
    node-selector: omega
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2022.8.6@sha256:3c3f508b3b79383bef875f79c45d688a59c945a0f4aa93ffeacf76bc84de81e2
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-pvc
        mountPath: /config
        accessMode: "ReadWriteOnce"
        size: 30Gi
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Home Assistant"
          hajimari.io/icon: "home-assistant"
        hosts:
          - host: home.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - home.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    dnsConfig:
      options:
        - name: ndots
          value: "1"
    hostNetwor: true
    dnsPolicy: ClusterFirstWithHostNet
