---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/home.sparks.codes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: home-assistant
              operator: In
              values:
                - "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: home
spec:
  volumeName: home-assistant-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 8Gi
