---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-cfg
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 5Gi
