---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    env:
      TZ: "America/Chicago"
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - home
          - media
          - monitoring
          - networking
          - gitlab
      name: "Sparks"
      customApps:
        - name: Habitica
          url: https://habitica.com
          icon: "check-bold"
        - name: Alpha
          url: http://alpha.sparks.codes
          icon: "desktop-classic"
        - name: PfSense Router
          url: https://router.sparks.codes
          icon: "router-network"
        - name: PiHole Adblock
          url: https://adblock.sparks.codes
          icon: "card-off"
        - name: Gitlab
          url: https://gitlab.imake.software
          icon: "gitlab"
        - name: Home Assistant
          url: https://home.sparks.codes
          icon: "home-assistant"
        - name: Z-Wave Controller
          url: https://zwavejs2mqtt.sparks.codes
          icon: "z-wave"
        - name: Zigbee Controller
          url: https://zigbee2mqtt.sparks.codes
          icon: "zigbee"
        - name: Photos
          url: https://photos.sparks.codes
          icon: "image-multiple"
        - name: Jellyfin Media
          url: https://media.sparks.codes
          icon: "play-network"
        - name: Paperless Documents
          url: https://paperless.sparks.codes
          icon: "newspaper-variant-multiple-outline"
        - name: Rook Storage
          url: https://rook.sparks.codes
          icon: "database"
        - name: Cryptofolio
          url: https://crypto.sparks.codes
          icon: "currency-btc"
        - name: Transmission
          url: https://transmission.sparks.codes
          icon: "web"
        - name: Agent NVR
          url: https://nvr.sparks.codes
          icon: "webcam"
        - name: PXE Server
          url: https://pxe.sparks.codes
          icon: "refresh-auto"
        - name: Whiskey iDRAC
          url: https://idrac-whiskey.sparks.codes
          icon: "remote-desktop"
        - name: Foxtrot iDRAC
          url: https://idrac-foxtrot.sparks.codes
          icon: "remote-desktop"
        - name: Lambda iDRAC
          url: https://idrac-lambda.sparks.codes
          icon: "remote-desktop"
        - name: Omega iDRAC
          url: https://idrac-omega.sparks.codes
          icon: "remote-desktop"
        - name: Dome Camera 1
          url: http://dome-camera-1.sparks.codes
          icon: "webcam"
        - name: Dome Camera 2
          url: http://dome-camera-2.sparks.codes
          icon: "webcam"
        - name: Printer
          url: https://printer.sparks.codes
          icon: "printer"
        - name: TV Tuner 1
          url: https://tv-tuner-1.sparks.codes
          icon: "television-classic"
        - name: TV Tuner 2
          url: https://tv-tuner-2.sparks.codes
          icon: "television-classic"
      groups:
        - name: Kubernetes
          links:
            - name: SparksD2145/flux-infra
              url: "https://github.com/sparksd2145/flux-infra"
            - name: christianmetal3/home-infra
              url: https://github.com/christianmetal3/home-infra
            - name: k8s-at-home Charts
              url: "https://github.com/k8s-at-home/charts/tree/master/charts"
        - name: Services
          links:
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
            - name: Namecheap
              url: "https://namecheap.com"
            - name: Drive
              url: "https://drive.google.com"
        - name: Finance
          links:
            - name: OneFinance
              url: "https://onefinance.com"
            - name: Mint
              url: "https://mint.com"
            - name: Credit Karma
              url: "https://creditkarma.com"
            - name: Chase
              url: "https://chase.com"
            - name: PayPal
              url: "https://paypal.com"
            - name: Charles Schwab
              url: "https://www.schwab.com/"
        - name: Shopping
          links:
            - name: eBay
              url: "https://ebay.com/"
            - name: Craigslist
              url: "https://sanantonio.craigslist.com/"
            - name: FB Marketplace
              url: "https://facebook.com/marketplace"
        - name: Media
          links:
            - name: YouTube
              url: "https://youtube.com/"
            - name: YouTube Music
              url: "https://music.youtube.com/"
            - name: My Soundcloud
              url: "https://soundcloud.com/SparksD2145"
        - name: Cryptocurrency
          links:
            - name: 2Miners ETH
              url: https://eth.2miners.com/account/0xD4145bEFDDE842f3Cbc8ce1a1d1094fD6d242eFf#farms
            - name: ETH Profitability Calculator
              url: https://www.cryptocompare.com/mining/calculator/eth
            - name: Coinbase
              url: https://www.coinbase.com/dashboard
            - name: Yieldly
              url: https://yieldly.finance/app
            - name: Guarda
              url: https://guarda.com

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
        hosts:
          - host: "dashboard.sparks.codes"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - dashboard.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128M
