---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.1.0
    env:
      TZ: "America/Chicago"
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - home
          - media
          - monitoring
          - networking
          - gitlab
      name: "Sparks"
      customApps:
        - name: Alpha
          url: http://alpha.sparks.codes
          icon: "desktop-classic"
        - name: PfSense Router
          url: https://router.sparks.codes
          icon: "router-network"
        - name: PiHole Adblock
          url: http://adblock.sparks.codes
          icon: "card-off"
        - name: Gitlab
          url: https://gitlab.imake.software
          icon: "gitlab"
        - name: Home Assistant
          url: https://home.sparks.codes
          icon: "home-assistant"
        - name: Z-Wave Controller
          url: http://zwavejs2mqtt.sparks.codes
          icon: "z-wave"
        - name: Zigbee Controller
          url: https://zigbee2mqtt.sparks.codes
          icon: "zigbee"
        - name: Photos
          url: https://photos.sparks.codes
          icon: "image-multiple"
        - name: Jellyfin Media
          url: https://media.sparks.codes
          icon: "play-network"
        - name: Paperless Documents
          url: https://paperless.sparks.codes
          icon: "newspaper-variant-multiple-outline"
        - name: Rook Storage
          url: https://rook.sparks.codes
          icon: "database"
        - name: Syncthing
          url: https://sync.sparks.codes
          icon: "sync"
        - name: Transmission
          url: https://transmission.sparks.codes
          icon: "web"
        - name: Agent NVR
          url: http://nvr.sparks.codes
          icon: "webcam"
        - name: PXE Server
          url: https://pxe.sparks.codes
          icon: "refresh-auto"
        - name: Whiskey iDRAC
          url: https://idrac-whiskey.sparks.codes
          icon: "remote-desktop"
        - name: Foxtrot iDRAC
          url: https://idrac-foxtrot.sparks.codes
          icon: "remote-desktop"
        - name: Lambda iDRAC
          url: https://idrac-lambda.sparks.codes
          icon: "remote-desktop"
        - name: Omega iDRAC
          url: https://idrac-omega.sparks.codes
          icon: "remote-desktop"
        - name: Dome Camera 1
          url: http://dome-camera-1.sparks.codes
          icon: "webcam"
        - name: Dome Camera 2
          url: http://dome-camera-2.sparks.codes
          icon: "webcam"
        - name: Printer
          url: https://printer.sparks.codes
          icon: "printer"
        - name: TV Tuner 1
          url: https://tv-tuner-1.sparks.codes
          icon: "television-classic"
        - name: TV Tuner 2
          url: https://tv-tuner-2.sparks.codes
          icon: "television-classic"
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
            - name: flux-infra
              url: "https://github.com/sparksd2145/flux-infra"
        # - name: Design
        #   links:
        #     - name: Awwwards
        #       url: "https://awwwards.com"
        #     - name: Dribbble
        #       url: "https://dribbble.com"
        #     - name: Muz.li
        #       url: "https://medium.muz.li/"
        # - name: Dev
        #   links:
        #     - name: Codepen
        #       url: "https://codepen.io/"
        #     - name: Devdocs
        #       url: "https://devdocs.io"
        #     - name: Devhints
        #       url: "https://devhints.io"
        # - name: Lifestyle
        #   links:
        #     - name: Design Milk
        #       url: "https://design-milk.com/category/interior-design/"
        #     - name: Dwell
        #       url: "https://www.dwell.com/"
        #     - name: Freshome
        #       url: "https://www.mymove.com/freshome/"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
            # - name: Trakt
            #   url: "http://trakt.tv"
            # - name: YouTube
            #   url: "https://youtube.com/feed/subscriptions"
        - name: Reading
          links:
            # - name: Instapaper
            #   url: "https://www.instapaper.com/u"
            # - name: Medium
            #   url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            # - name: The Verge
            #   url: "https://theverge.com/"
            # - name: MIT Technology Review
            #   url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "dashboard.sparks.codes"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - dashboard.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config-v1
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128M
