---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    env:
      TZ: "America/Chicago"
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - home
          - media
          - monitoring
          - networking
          - gitlab
      name: "Sparks"
      customApps:
        - name: Alpha
          url: http://alpha.sparks.codes
          icon: "desktop-classic"
        - name: PfSense Router
          url: https://router.sparks.codes
          icon: "router-network"
        - name: PiHole Adblock
          url: https://adblock.sparks.codes
          icon: "card-off"
        - name: Gitlab
          url: https://gitlab.imake.software
          icon: "gitlab"
        - name: Home Assistant
          url: https://home.sparks.codes
          icon: "home-assistant"
        - name: Z-Wave Controller
          url: https://zwavejs2mqtt.sparks.codes
          icon: "z-wave"
        - name: Zigbee Controller
          url: https://zigbee2mqtt.sparks.codes
          icon: "zigbee"
        - name: Photos
          url: https://photos.sparks.codes
          icon: "image-multiple"
        - name: Jellyfin Media
          url: https://media.sparks.codes
          icon: "play-network"
        - name: Paperless Documents
          url: https://paperless.sparks.codes
          icon: "newspaper-variant-multiple-outline"
        - name: Rook Storage
          url: https://rook.sparks.codes
          icon: "database"
        - name: Transmission
          url: https://transmission.sparks.codes
          icon: "web"
        - name: Agent NVR
          url: https://nvr.sparks.codes
          icon: "webcam"
        - name: PXE Server
          url: https://pxe.sparks.codes
          icon: "refresh-auto"
        - name: Whiskey iDRAC
          url: https://idrac-whiskey.sparks.codes
          icon: "remote-desktop"
        - name: Foxtrot iDRAC
          url: https://idrac-foxtrot.sparks.codes
          icon: "remote-desktop"
        - name: Lambda iDRAC
          url: https://idrac-lambda.sparks.codes
          icon: "remote-desktop"
        - name: Omega iDRAC
          url: https://idrac-omega.sparks.codes
          icon: "remote-desktop"
        - name: Dome Camera 1
          url: http://dome-camera-1.sparks.codes
          icon: "webcam"
        - name: Dome Camera 2
          url: http://dome-camera-2.sparks.codes
          icon: "webcam"
        - name: Printer
          url: https://printer.sparks.codes
          icon: "printer"
        - name: TV Tuner 1
          url: https://tv-tuner-1.sparks.codes
          icon: "television-classic"
        - name: TV Tuner 2
          url: https://tv-tuner-2.sparks.codes
          icon: "television-classic"
      groups:
        - name: Kubernetes
          links:
            - name: flux-infra
              url: "https://github.com/sparksd2145/flux-infra"
            - name: k8s-at-home Charts
              url: "https://github.com/k8s-at-home/charts/tree/master/charts"
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
            - name: YouTube
              url: "https://youtube.com/"
        - name: Reading
          links:
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
        hosts:
          - host: "dashboard.sparks.codes"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - dashboard.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128M
