---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ceph-filesystem"
  resources:
    requests:
      storage: 1Gi
