---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 15m
  values:
    dualStack:
      # -- set this to true to enable creation of DualStack services or creation of separate IPv6 services if `serviceDns.type` is set to `"LoadBalancer"`
      enabled: false
    # -- Configuration for the DNS service on port 53
    serviceDns:
      # -- deploys a mixed (TCP + UDP) Service instead of separate ones
      mixedService: false

      # -- `spec.type` for the DNS Service
      type: LoadBalancer

      # -- The port of the DNS service
      port: 53

      # -- `spec.externalTrafficPolicy` for the DHCP Service
      externalTrafficPolicy: Local

      # -- A fixed `spec.loadBalancerIP` for the DNS Service
      loadBalancerIP: 10.10.201.2

      # -- Annotations for the DNS service
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        # metallb.universe.tf/address-pool: network-services
        # metallb.universe.tf/allow-shared-ip: pihole-svc

    # -- Configuration for the DHCP service on port 67
    serviceDhcp:

      # -- Generate a Service resource for DHCP traffic
      enabled: false

      # -- `spec.type` for the DHCP Service
      type: NodePort

      # -- The port of the DHCP service
      port: 67

      # -- Optional node port for the DHCP service
      nodePort: ""

      # -- `spec.externalTrafficPolicy` for the DHCP Service
      externalTrafficPolicy: Local

      # -- A fixed `spec.loadBalancerIP` for the DHCP Service
      loadBalancerIP: ""
      # -- A fixed `spec.loadBalancerIP` for the IPv6 DHCP Service
      loadBalancerIPv6: ""

      # -- Annotations for the DHCP service
      annotations: {}

    # -- Configuration for the web interface service
    serviceWeb:
      # -- Configuration for the HTTP web interface listener
      http:
        # -- Generate a service for HTTP traffic
        enabled: true

        # -- The port of the web HTTP service
        port: 80

      # -- Configuration for the HTTPS web interface listener
      https:
        # -- Generate a service for HTTPS traffic
        enabled: true

        # -- The port of the web HTTPS service
        port: 443

      # -- `spec.type` for the web interface Service
      type: LoadBalancer

      # -- `spec.externalTrafficPolicy` for the web interface Service
      externalTrafficPolicy: Local

      # -- A fixed `spec.loadBalancerIP` for the web interface Service
      loadBalancerIP: 10.10.201.2

      # -- Annotations for the DHCP service
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc

    virtualHost: adblock.sparks.codes

    # -- Configuration for the Ingress
    ingress:
      # -- Generate a Ingress resource
      enabled: true
      # -- Annotations for the ingress
      path: /
      ingressClassName: nginx-internal
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "Pihole"
        hajimari.io/icon: "card-off"
      hosts:
        - adblock.sparks.codes
      tls:
        - secretName: acme-crt-secret-sparks-codes
          hosts:
            - adblock.sparks.codes

    # -- `spec.PersitentVolumeClaim` configuration
    persistentVolumeClaim:
      # -- set to true to use pvc
      enabled: true
      # -- specify an existing `PersistentVolumeClaim` to use
      existingClaim: pihole-data-pvc
      accessModes:
        - ReadWriteMany
      size: "1Gi"

    adminPassword: ${NETWORKING_PIHOLE_ADMIN_PASSWORD}

    extraEnvVars:
      TZ: "America/Chicago"

    # -- default upstream DNS 1 server to use
    DNS1: "10.10.201.6"
    # -- default upstream DNS 2 server to use
    DNS2: "127.0.0.1"

    dnsmasq:
      # -- Add upstream dns servers. All lines will be added to the pihole dnsmasq configuration
      upstreamServers: []
      # - server=/foo.bar/192.168.178.10
      # - server=/bar.foo/192.168.178.11

      # -- Add custom dns entries to override the dns resolution. All lines will be added to the pihole dnsmasq configuration.
      customDnsEntries: []
      # - address=/foo.bar/192.168.178.10
      # - address=/bar.foo/192.168.178.11

      # -- Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
      additionalHostsEntries: []
      # - 192.168.0.3     host4
      # - 192.168.0.4     host5

      # -- Static DHCP config
      staticDhcpEntries: []
      # staticDhcpEntries:
      # - dhcp-host=MAC_ADDRESS,IP_ADDRESS,HOSTNAME

      # -- Other options
      customSettings:
      # otherSettings:
      # - rebind-domain-ok=/plex.direct/

      # -- Here we specify custom cname entries that should point to `A` records or
      # elements in customDnsEntries array.
      # The format should be:
      #  - cname=cname.foo.bar,foo.bar
      #  - cname=cname.bar.foo,bar.foo
      #  - cname=cname record,dns record
      customCnameEntries: []
      # Here we specify custom cname entries that should point to `A` records or
      # elements in customDnsEntries array.
      # The format should be:
      #   - cname=cname.foo.bar,foo.bar
      #   - cname=cname.bar.foo,bar.foo
      #   - cname=cname record,dns record

    # -- list of whitelisted domains to import during initial start of the container
    whitelist: {}

    # -- list of blacklisted domains to import during initial start of the container
    blacklist: {}

    # -- list of blacklisted regex expressions to import during initial start of the container
    regex: {}
      # Add regular expression blacklist items
      # - (^|\.)facebook\.com$

    # -- values that should be added to pihole-FTL.conf
    ftl: {}
      # Add values for pihole-FTL.conf
      # MAXDBDAYS: 14

    # -- port the container should use to expose HTTP traffic
    webHttp: "80"

    # -- port the container should use to expose HTTPS traffic
    webHttps: "443"

    # -- hostname of pod
    hostname: "adblock"

    # -- should the container use host network
    hostNetwork: "false"

    # -- should container run in privileged mode
    privileged: "false"

    customVolumes:
      # -- set this to true to enable custom volumes
      enabled: false
      # -- any volume type can be used here
      config: {}
        # hostPath:
        #   path: "/mnt/data"

    # -- any extra volumes you might want
    extraVolumes: {}
      # external-conf:
      #   configMap:
      #     name: pi-hole-lighttpd-external-conf

    # -- any extra volume mounts you might want
    extraVolumeMounts: {}
      # external-conf:
      #   mountPath: /etc/lighttpd/external.conf
      #   subPath: external.conf

    # -- Additional annotations for pods
    podAnnotations: {}
      # Example below allows Prometheus to scape on metric port (requires pihole-exporter sidecar enabled)
      # prometheus.io/port: '9617'
      # prometheus.io/scrape: 'true'

    monitoring:
      # -- Preferably adding prometheus scrape annotations rather than enabling podMonitor.
      podMonitor:
        # -- set this to true to enable podMonitor
        enabled: false
      # -- Sidecar configuration
      sidecar:
        # -- set this to true to enable podMonitor as sidecar
        enabled: false
        port: 9617
        image:
          repository: ekofr/pihole-exporter
          tag: v0.3.0
          pullPolicy: IfNotPresent
        resources:
          limits:
            memory: 128Mi
          # requests:
          #  cpu: 100m
          #  memory: 128Mi

    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 10.10.201.6
