---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: beammp-cwh11
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: beammp-server
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: gitlab-imake-software
        namespace: flux-system
      interval: 15m
  values:
    image:
      tag: latest
      pullPolicy: Always
    # nodeSelector:
    #   services/minecraft: active
    resources:
      requests:
        memory: 4096Mi
        cpu: 2000m
    persistence:
      data:
        enabled: false
        existingClaim: local-beammp-cwh11
    service:
      main:
        primary: false
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            primary: true
            port: 80
            protocol: TCP
      beammp-tcp:
        enabled: true
        primary: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: beammp
        ports:
          beamng-tcp:
            enabled: true
            primary: true
            port: 30814
            protocol: TCP
      beammp-udp:
        enabled: true
        primary: false
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: beammp
        ports:
          beamng-udp:
            enabled: true
            primary: true
            port: 30814
            protocol: UDP
    envFrom:
      - configMapRef:
          name: beammp-env-config
    configmap:
      env-config:
        enabled: true
        data:
          AUTH_KEY: ""
          DEBUG: "true"
          PRIVATE: "true"
          DESC: "test"
          NAME: "name"
          MAP: "/levels/gridmap_v2/info.json"
          CARS: "1"
          MAX_PLAYERS: "10"
          PORT: "30814"
          ADDITIONAL_SERVER_CONFIG_TOML: |
            # Additional Config
