---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-beammp-cwh11
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 45Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/games-raid1/beammp.sparks.codes/cwh11
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - tango

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-beammp-cwh11
  namespace: games
spec:
  volumeName: local-beammp-cwh11
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 45Gi
