---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-proxy-router-sparks-codes
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 9.3.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: ClusterIP
    serverBlock: |-
      server {
        listen       8080;
        server_name  router.sparks.codes;

        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_request_buffering off;
          proxy_ssl_verify off;

          # resolver 10.10.0.1;
          set $backend "https://10.10.0.1";
          proxy_pass $backend;
        }

        location ~ /\.ht {
          deny  all;
        }
      }
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        ingress.kubernetes.io/force-ssl-redirect: "true"
      hostname: "router.sparks.codes"
      extraTls:
        - hosts:
            - router.sparks.codes
          secretName: acme-crt-secret-sparks-codes
