---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: rook-charts
        namespace: flux-system
      interval: 5m
  values:
    monitoring:
      enabled: false
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: nginx
        host:
          name: rook.sparks.codes
          path: "/"
        tls:
          - hosts:
              - rook.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    cephClusterSpec:
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          metadataDevice:
          osdsPerDevice: "1"
        nodes:
          - name: whiskey
            devices:
              - name: /dev/disk/by-id/scsi-SATA_ST2000DM006-2DM1_Z4ZBHPQB
              - name: /dev/disk/by-id/scsi-SATA_ST2000DM006-2DM1_Z4ZC3MTY
              - name: /dev/disk/by-id/scsi-SATA_ST2000DM006-2DM1_Z560VAE4
              - name: /dev/disk/by-id/scsi-SATA_ST2000DM008-2FR1_ZFL068C2
              - name: /dev/disk/by-id/scsi-SATA_ST2000VN004-2E41_Z525MFKA
              - name: /dev/disk/by-id/scsi-SATA_ST2000VN004-2E41_Z52B90Y9
          - name: foxtrot
            devices:
              - name: /dev/disk/by-id/scsi-3500000e01f068b20
              - name: /dev/disk/by-id/scsi-3500000e01f06b880
              - name: /dev/disk/by-id/scsi-35000c5003609f44d
              - name: /dev/disk/by-id/scsi-35000c5004d032bcf
              - name: /dev/disk/by-id/scsi-35000c500b40310fb
              - name: /dev/disk/by-id/scsi-35000c500b4031499
          - name: lambda
            devices:
              - name: /dev/disk/by-id/scsi-SDELL_PERC_H310_004a12ec044f4da925002f49e5a0a38c
          - name: omega
            devices:
              - name: /dev/disk/by-id/scsi-SDELL_PERC_H710_001d5d1106de2edb2400af09e260f681-part1
