---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-proxy-idrac-omega-sparks-codes
  namespace: nginx
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: nginx
      version: 9.5.16
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    service:
      type: ClusterIP
    serverBlock: |-
      server {
        listen       8080;
        server_name  idrac.omega.sparks.codes;

        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_request_buffering off;
          proxy_ssl_verify off;

          resolver 10.10.0.1;
          set $backend "https://idrac-omega.sparks.codes";
          proxy_pass $backend;
        }

        location ~ /\.ht {
          deny  all;
        }
      }
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx-internal"
        ingress.kubernetes.io/force-ssl-redirect: "true"
      hostname: "idrac.omega.sparks.codes"
      extraTls:
        - hosts:
            - idrac.omega.sparks.codes
          secretName: acme-crt-secret-sparks-codes
