---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
      PHOTOPRISM_ADMIN_PASSWORD: "photoprism45@"
      # -- Photoprism storage path
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      # -- Photoprism originals path
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      # -- Disable authentication / password protection
      PHOTOPRISM_PUBLIC: "false"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-internal
          nginx.ingress.kubernetes.io/proxy-body-size: 2G
        hosts:
          - host: photos.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - photos.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 35Gi
        retain: true

      originals:
        enabled: true
        mountPath: "/photoprism/originals"
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 2Ti
        retain: true
