---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-photoprism-imports
spec:
  capacity:
    storage: 55Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: omega.sparks.codes
    path: "/mnt/static/photos.sparks.codes/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-photoprism-imports
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 55Gi
