---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-photoprism-imports
spec:
  capacity:
    storage: 55Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/static/photos.sparks.codes/import
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-photoprism-imports
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 55Gi
