---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: lan-services
spec:
  interval: 5m
  chart:
    spec:
      chart: zwavejs2mqtt
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    additionalVolumeMounts:
      - name: usb
        mountPath: /dev/serial/by-id/usb-0658_0200-if00
    additionalVolumes:
      - name: usb
        hostPath:
          path: /dev/serial/by-id/usb-0658_0200-if00
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: zwave-controller
                  operator: In
                  values:
                    - "true"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: zwavejs2mqtt.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - zwavejs2mqtt.sparks.codes
            secretName: acme-crt-secret-sparks-codes

    persistence:
      config:
        enabled: true
