apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bookstack-docs
  - ispy-dvr
  - hajimari
  - nfs-home.yaml
  - home-assistant
  - mosquitto-mqtt
  - zigbee2mqtt
  - zwavejs2mqtt
