---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
        hosts:
          - host: youtubedl.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - youtubedl.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      config:
        enabled: true
        size: 25Gi
      media:
        enabled: true
        type: pvc
        existingClaim: local-jellyfin
        retain: true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Ti
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/static/jellyfin-media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-jellyfin
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
