apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cspc-ha
  namespace: openebs
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: "whiskey"
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: blockdevice-83f7e24735158a13b233468ac3fd05c7
            - blockDeviceName: blockdevice-94d2c67f20485e78616408869d6ce46b
      poolConfig:
        dataRaidGroupType: "stripe"

    - nodeSelector:
        kubernetes.io/hostname: "foxtrot"
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: blockdevice-1ecd7eaa1058f1dfbc45b54b014a7fd1
            - blockDeviceName: blockdevice-3e003568b68db9ba09858a3d30eef77d
      poolConfig:
        dataRaidGroupType: "stripe"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cstor-sc-ha
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  replicaCount: "2"
  cstorPoolCluster: "cspc-ha"
  cas-type: "cstor"
