---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack-docs
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bookstack
      version: 3.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  values:
    env:
      TZ: "America/Chicago"
      APP_URL: "http://docs.sparks.codes"
      DB_HOST: localhost
      DB_USER: bookstack
      DB_PASS: bookstack
      DB_DATABASE: bookstack
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: docs.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - docs.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    mariadb:
      enabled: true
      architecture: standalone
      auth:
        database: bookstack
        username: bookstack
        password: bookstack
      primary:
        persistence:
          enabled: true
          existingClaim: bookstack-docs-data
