---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10gbe-tango
    path: "/mnt/local/storage/k8s-nfs/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 600Gi
