---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvr-sparks-codes-media
  namespace: home
spec:
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
