---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvr-sparks-codes-commands
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ceph-filesystem"
  resources:
    requests:
      storage: 500Mi
