---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvr-sparks-codes-commands
  namespace: home
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
