---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bungeecord-proxy
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-proxy
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 15m
  values:
    minecraftProxy:
      type: BUNGEECORD
      serviceType: LoadBalancer
      loadBalancerIP: 10.10.202.1
      rcon:
        enabled: true
        password: "minecraft2145"
        serviceType: ClusterIP
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-bungee-pvc
