---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bungeecord-proxy
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-proxy
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 15m
  values:
    minecraftProxy:
      type: BUNGEECORD
      serviceType: LoadBalancer
      loadBalancerIP: 10.10.201.1
      rcon:
        enabled: true
        password: "minecraft2145"
        serviceType: ClusterIP
    persistence:
      dataDir:
        enabled: true
        existingClaim: local-mc-bungee
        size: 256Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mc-bungee
  labels:
    app: minecraft-bungeecord-proxy-minecraft-proxy
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 256Mi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/static/mc.sparks.codes/bungee
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mc-bungee
  namespace: games
  labels:
    app: minecraft-bungeecord-proxy-minecraft-proxy
spec:
  volumeName: local-mc-bungee
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 256Mi
