---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bungee-pvc
  namespace: games
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ceph-filesystem"
  resources:
    requests:
      storage: 20Gi
