---
- hosts: servers
  become: true
  tasks:
    - name: Add Nvidia Repo
      shell: |
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
        && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
        && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

    - name: Install Packages
      apt:
        update_cache: "yes"
        pkg:
          - tmux
          - python3
          - python3-pip
          - nvidia-headless-470-server
          - xserver-xorg-video-nvidia-470-server
          - nvidia-utils-470-server
          - nvidia-cuda-toolkit
          - nvidia-settings
          - nvidia-docker2

    - name: Install bottle python package
      pip:
        name: coolgpus

    - name: Set text target
      shell: systemctl set-default multi-user.target

    - name: Install Containerd Template
      copy:
        src: config.toml.tmpl
        dest: /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl

    - name: Install Docker Config
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
              "default-runtime": "nvidia",
              "runtimes": {
                  "nvidia": {
                      "path": "nvidia-container-runtime",
                      "runtimeArgs": []
                  }
              }
          }
