---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bungeecord-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft-proxy
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 5m
  values:
    minecraftProxy:
      type: BUNGEECORD
      serviceType: LoadBalancer
      loadBalancerIP: 10.10.201.1
      config: |
        listeners:
          - query_port: 25577
            motd: mc.sparks.codes
            tab_list: SERVER
            query_enabled: false
            proxy_protocol: false
            forced_hosts:
              cwh11.mc.sparks.codes: cwh11
              testing.mc.sparks.codes: testing
            ping_passthrough: true
            bind_local_address: true
            host: 0.0.0.0:25577
            priorities:
              - cwh11
            max_players: -1
            tab_size: 60
            force_default_server: false
        remote_ping_cache: -1
        network_compression_threshold: 256
        permissions:
          default:
            - bungeecord.command.server
            - bungeecord.command.list
          admin:
            - bungeecord.command.alert
            - bungeecord.command.end
            - bungeecord.command.ip
            - bungeecord.command.reload
        log_pings: true
        connection_throttle_limit: 3
        server_connect_timeout: 5000
        timeout: 30000
        stats: a81df59a-168e-445d-87b1-9b946a5547a3
        player_limit: 25
        ip_forward: true
        groups:
          SuperDigDug:
            - admin
        remote_ping_timeout: 5000
        connection_throttle: 4000
        log_commands: false
        prevent_proxy_connections: false
        online_mode: true
        forge_support: false
        disabled_commands:
          - disabledcommandhere
        servers:
          testing:
            motd: testing.mc.sparks.codes
            address: 10.10.201.2:25565
            restricted: false
          superdigdug:
            motd: superdigdug.mc.sparks.codes
            address: 10.10.2.2:25566
            restricted: false
          cwh11:
            motd: cwh11.mc.sparks.codes
            address: 10.10.2.2:25567
            restricted: false
