---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haste-server
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: haste-server
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Haste"
          hajimari.io/icon: "text"
        hosts:
          - host: haste.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - haste.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      config:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 2Gi
