---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-samba
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: America/Chicago
      RECYCLE: "false"
      # PERMISSIONS: "true"
      SHARE1: bungee;/share/samba/share1;yes;no
      SHARE2: cwh11;/share/samba/share2;yes;no
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.10.201.0
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 445
          netbios:
            enabled: true
            protocol: TCP
            port: 139
    persistence:
      share1:
        enabled: true
        existingClaim: minecraft-bungee-pvc
        accessMode: ReadWriteMany
        mountPath: /share/samba/share1
      share2:
        enabled: true
        existingClaim: minecraft-cwh11-pvc
        accessMode: ReadWriteMany
        mountPath: /share/samba/share2
