---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 2.11.0
      sourceRef:
        kind: HelmRepository
        name: openebs-charts
        namespace: flux-system
      interval: 5m
  values:
    crd:
      enableInstall: true
    webhook:
      enabled: false
