---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfty-push-notifications
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: ntfy
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-external
          hajimari.io/enable: "true"
          hajimari.io/appName: "Notify"
          hajimari.io/icon: "bell-ring"
        hosts:
          - host: notify.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - notify.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      cache:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true
      config:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true
