---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-pxe-sparks-codes
  namespace: nginx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: nginx
      version: 9.5.13
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    extraVolumeMounts:
      - mountPath: "/app"
        subPath: "pxe.sparks.codes"
        name: nfsvol
    extraVolumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: nfs-nginx
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx-internal"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/server-snippet: |
          autoindex on;
      hostname: "pxe.sparks.codes"
      extraTls:
        - hosts:
            - pxe.sparks.codes
          secretName: acme-crt-secret-sparks-codes
