---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  selector:
    matchLabels:
      run: zwavejs2mqtt
  replicas: 1
  template:
    metadata:
      labels:
        run: zwavejs2mqtt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zwave-controller
                    operator: In
                    values:
                      - "true"
      containers:
        - name: zwavejs2mqtt
          image: zwavejs/zwavejs2mqtt
          env:
            - name: NETWORK_KEY
            - name: TZ
              value: "America/Chicago"
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
            - name: zwavejs
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/store
              subPath: zwavejs2mqtt.sparks.codes
            - name: usb
              mountPath: /dev/ttyACM0
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8091
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8091
            timeoutSeconds: 1
          securityContext:
            privileged: true
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8091
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-home
        - name: usb
          hostPath:
            path: /dev/ttyACM0

---
apiVersion: v1
kind: Service
metadata:
  name: zwavejs2mqtt
  namespace: home
  labels:
    run: home
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8091
      protocol: TCP
    - name: ws
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.10.200.4
  selector:
    run: zwavejs2mqtt
