---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minecraft
  namespace: metallb-system
spec:
  addresses:
    - 10.10.202.0/24
  autoAssign: false
status: {}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: minecraft
  namespace: metallb-system
spec:
  ipAddressPools:
    - minecraft
status: {}
