---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: mqtt-controller
                  operator: In
                  values:
                    - "true"
    env:
      TZ: "America/Chicago"
    persistence:
      data:
        enabled: true
        mountPath: /data
        accessMode: "ReadWriteOnce"
        size: 1Gi
        existingClaim: mosquitto-data
        subPath: mqtt.sparks.codes
    service:
      main:
        enabled: true
        mqtt:
          enabled: true
          port: 1883
        type: LoadBalancer
        loadBalancerIP: 10.10.200.3
