---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: eclipse-mosquitto
      tag: latest
    node-selector: omega
    env:
      TZ: "America/Chicago"
    persistence:
      configinc:
        enabled: true
        size: 512Mi
        existingClaim: mosquitto-config-pvc
      data:
        enabled: false
        mountPath: /data
        accessMode: "ReadWriteOnce"
        size: 2Gi
        existingClaim: mosquitto-data-pvc
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
        type: LoadBalancer
        loadBalancerIP: 10.10.201.3
