---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Mi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/mqtt.sparks.codes/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rpi4-poe-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config-pvc
  namespace: home
spec:
  volumeName: mosquitto-config-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 512Mi
