---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-k6-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: ceph-block
