---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser-data-sparks-codes
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: filebrowser
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          hajimari.io/enable: "true"
          hajimari.io/appName: "File Browser"
          hajimari.io/icon: "file-download"
          nginx.ingress.kubernetes.io/client-body-buffer-size: "10g"
          nginx.ingress.kubernetes.io/proxy-body-size: "10g"
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
        hosts:
          - host: data.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - data.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: local-data-sparks-codes-config
      data:
        enabled: true
        type: pvc
        existingClaim: local-data-sparks-codes-data
        retain: true
