---
- hosts: servers
  become: true
  tasks:
    - name: Correct Timezone
      shell: TZ="America/Chicago" ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

    - name: Install Latest Packages
      apt:
        name: "*"
        state: latest

    - name: Install Packages
      apt:
        pkg:
          - lvm2
          - nfs-common

    - name: Start K3s Worker
      shell: curl -sfL https://get.k3s.io | K3S_URL='https://omega.sparks.codes:6443' K3S_TOKEN='K106dabf48ea0e968951a7ff8c7615581f8a0650932ef18a131d1cb8688c55693b1::server:caf3fc6d264c73ff136e5ace0d8f2816' sh -
