---
- hosts: servers
  become: true
  tasks:
    - name: Correct Timezone
      shell: TZ="America/Chicago" ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

    - name: Install Packages
      apt:
        pkg:
          - lvm2
          - nfs-kernel-server

    - name: Start K3s Master
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest sh -s - server --flannel-backend=host-gw --no-deploy=traefik,servicelb,local-storage --disable=traefik,servicelb,local-storage
