---
- hosts: servers
  become: true
  tasks:
    - name: Correct Timezone
      shell: TZ="America/Chicago" ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

    - name: Install Latest Packages
      apt:
        name: "*"
        state: latest

    - name: Install Packages
      apt:
        pkg:
          - lvm2
          - nfs-common

    - name: Start K3s Worker
      shell: curl -sfL https://get.k3s.io | K3S_URL='https://omega.sparks.codes:6443' K3S_TOKEN='K100cc4b9e3e45a2011700522184662c1e81c1375fe5d94440c2d3f891e9ea969fb::server:f92e53cb3b7e6bbe71829ed98690ded6' sh -
