---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: lan-services
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      data:
        enabled: true
        mountPath: /data
        accessMode: "ReadWriteOnce"
        size: 400M
    service:
      main:
        enabled: true
        mqtt:
          enabled: true
          port: 1883
        type: LoadBalancer
        loadBalancerIP: 10.11.0.3
