---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ceph-filesystem"
  resources:
    requests:
      storage: 2Gi
