---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-cwh11-broville
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 3.10.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-charts
        namespace: flux-system
      interval: 15m
  values:
    image: itzg/minecraft-server
    imageTag: latest
    nodeSelector:
      services/minecraft: active
    resources:
      requests:
        memory: 16384Mi
        cpu: 2000m
    minecraftServer:
      eula: "TRUE"
      version: "1.18.2"
      type: FORGE
      motd: "[broville] - cwh11.mc.sparks.codes"
      difficulty: normal
      ops: "superdigdug"
      worldSaveName: world_cwh11_broville
      maxPlayers: 20
      viewDistance: 14
      gameMode: survival
      pvp: true
      onlineMode: "TRUE"
      memory: 16384M
      serviceType: LoadBalancer
      loadBalancerIP: 10.10.202.3
      servicePort: 25566
    persistence:
      dataDir:
        enabled: true
        existingClaim: local-mc-cwh11-broville
