---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mc-cwh11-broville
  labels:
    app: minecraft-cwh11-broville-minecraft
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/static/mc.sparks.codes/cwh11-broville
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mc-cwh11-broville
  namespace: games
  labels:
    app: minecraft-cwh11-broville-minecraft
spec:
  volumeName: local-mc-cwh11-broville
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
