apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - addresspool.yaml
  - bfdprofile.yaml
  - bgpadvertisement.yaml
  - bgppeer.yaml
  - community.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml
