apiVersion: v1
kind: ConfigMap
metadata:
  name: pxe-sparks-codes-nginx-config
  namespace: networking
data:
  config: |
    server {
      listen        8080;
      server_name   pxe.sparks.codes;
      root          /app;

      location / {
        autoindex on;
      }
    }
