---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxe-sparks-codes-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ceph-filesystem"
  resources:
    requests:
      storage: 100Gi
