---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nfty-push-notifications
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: binwiederhier/ntfy
      tag: v1.17.2
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-external
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authelia.auth.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.sparks.codes?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Method $request_method;
          hajimari.io/enable: "true"
          hajimari.io/appName: "Notify"
          hajimari.io/icon: "bell-ring"
        hosts:
          - host: notify.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - notify.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      cache:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true
      config:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true
