---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2022.7.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts.yaml
        namespace: flux-system
      interval: 15m
  values:
    authentik:
      secret_key: ${AUTHENTIK-SECRET-KEY}
      error_reporting:
        enabled: false
      postgresql:
        password: "ThisIsNotASecurePassword"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-internal
        hajimari.io/enable: "true"
        hajimari.io/appName: "Authentik"
        hajimari.io/icon: "bulletin-board"
      hosts:
        - host: authentik.sparks.codes
          paths:
            - path: "/"
              pathType: "Prefix"
      tls:
        - hosts:
            - authentik.sparks.codes
          secretName: acme-crt-secret-sparks-codes
    postgresql:
      enabled: true
      postgresqlPassword: "ThisIsNotASecurePassword"
    redis:
      enabled: true
