---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2022.7.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 15m
  values:
    authentik:
      secret_key: ${TOOLS_AUTHENTIK_SECRET_KEY}
      error_reporting:
        enabled: false
      postgresql:
        password: ${TOOLS_AUTHENTIK_POSTGRESQL_PASSWORD}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-internal
        hajimari.io/enable: "true"
        hajimari.io/appName: "Authentik"
        hajimari.io/icon: "key"
      hosts:
        - host: authentik.sparks.codes
          paths:
            - path: "/"
              pathType: "Prefix"
      tls:
        - hosts:
            - authentik.sparks.codes
          secretName: acme-crt-secret-sparks-codes
    postgresql:
      enabled: true
      password: ${TOOLS_AUTHENTIK_POSTGRESQL_PASSWORD}
      postgresqlPassword: ${TOOLS_AUTHENTIK_POSTGRESQL_PASSWORD}
    redis:
      enabled: true
