---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: 5.1.1
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
      interval: 5m
  values:
    hosts:
      domain: imake.software
      hostSuffix:
      https: true
      externalIP:
      ssh: ~
      gitlab: {}
      minio: {}
      registry: {}
      tls: {}
      smartcard: {}
      kas: {}
      pages: {}
