---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: transmission
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/Chicago"
      TRANSMISSION_RPC_PASSWORD: "transmission2145"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-internal
          hajimari.io/enable: "true"
          hajimari.io/appName: "Transmission"
          hajimari.io/icon: "web"
        hosts:
          - host: transmission.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - transmission.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      downloads:
        enabled: true
        accessMode: ReadWriteMany
        existingClaim: nfs-transmission
        subPath: transmisson.sparks.codes
        size: 500Gi
