---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: omega.sparks.codes
    path: "/mnt/static"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
