---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: lan-services
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  values:
    DNS1: "10.10.0.1"
    DNS2: "127.0.0.1"
    podDnsConfig:
      enabled:
      policy: None
      nameservers:
        - 10.10.0.1

    virtualHost: adblock.sparks.codes

    serviceDhcp:
      enabled: false

    persistentVolumeClaim:
      enabled: true

    serviceWeb:
      loadBalancerIP: 10.10.200.2
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceDns:
      loadBalancerIP: 10.10.200.2
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
