---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool-ha
  namespace: openebs
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 4Gi
      - name: PoolResourceLimits
        value: |-
            memory: 8Gi
spec:
  name: cstor-disk-pool-ha
  type: disk
  maxPools: 4
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
      - blockdevice-684fc0e67501c223abb7e4494416dc91
      - blockdevice-7416bd5abdb2698b8f9f9de41065e6c0
      - blockdevice-a587418d9b13c5f79e82114ce3837ba3
      - blockdevice-ff8af16f8dc06ac936b835790be48180
      - blockdevice-8d0041fc5f741a3302f38a935e162cc1
      - blockdevice-5c9d20fc445ca8868a27044c954c0b03
      - blockdevice-f294158dba14d36df10ae2185bbdbc6e
      - blockdevice-13bf07ce3686ad053997ccb2363f71f0
      - blockdevice-9cf2457bee08d84b373ba7aec59d554b
      - blockdevice-90e7d1fab02aabeb00e1aa43039793da
      - blockdevice-265dfe55e45dcbc0eca8e331839f1d3c
      - blockdevice-1c44dfed358bd4ba8c37422d4ecc05d8
      - blockdevice-4299c6b3b154262bbfa242fafde6015f
      - blockdevice-400b0d62cdb05c91696e32b506ce3850
      - blockdevice-dd837bba5c1545807aa594d54d156d2d
provisioner: openebs.io/provisioner-iscsi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-disk-ha
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk-pool-ha"
      - name: ReplicaCount
        value: "4"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Retain
