---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: lan-services
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  values:
    DNS1: "10.10.0.1"
    DNS2: "8.8.4.4"

    serviceDhcp:
      enabled: false

    persistentVolumeClaim:
      enabled: true

    serviceWeb:
      loadBalancerIP: 10.10.0.32
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceDns:
      loadBalancerIP: 10.10.0.32
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
