{
    "data": "ENC[AES256_GCM,data:LI84bdcPbASo/OfZ2m59ZZFVQ2y7KtupishSzxvSNvAPnY+sPrgVNd/Zg70TjlvbIfIjvAN3mSngGl+vv6jk+VOqUOr/t241MYahth7gvBsPaB63a4an1U4ikWJ8IDtnEcr/7fLniAGs5ypiXslIi691Bq9B5rC5CFNgPOE2R2Ntu19mmDoxPRaCk94orGcOoK7RF6sUdOzZDWL2IJoNSQ==,iv:AroEtjjQyANA/5Z0teVHF5nHSVNX0H04xWlAX0Is8lw=,tag:aiwASAH2ppVL/zue6iO8tQ==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybDhHQzBORFFMSVZqbkxs\nUHU1cWhGbXVUbkhjcUVETHlSUUdBVzVYMEE0CkFZZEpaM2dqeE4rUVJ4NEZ6NWV5\nL3ZlMVA1STJ3T1ZQdjF0eXZKN0hXUTQKLS0tIFcxVmxYN3liWkRLVU05NjJ5VWlB\nMTQ3V1NpZ21vMnRIMnM5QjZMWWlMcDQKBV2eDcG5hM41HMzzhiKcNBuebDIk1fFF\nzVideh5BINEPaEzLYnuMm0FYMLmlfYP7x+OB5EViS5x2pGAYNa7ObQ==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-08-14T15:59:56Z",
        "mac": "ENC[AES256_GCM,data:uuFsLyWVKgzVqb3W4zxDqUBFpYu5pNyTDBMQRdqirZ1xJuWi6g5/Me3vLW5CsazFUoIFkT+Nu/jTnAA+8kQZ6yf4NIRP8F3F8yJw6kUpPW0Toph4PjwLWoMj9vg6ixf563ccEMIFoy6H+aSb36nDrahGa6MT4PK7ccXnGGvSNlM=,iv:mqDb8x0eATE5ObgsHWe8CQyfd9cUy3UOfcljddn2iD8=,tag:qGLgSwxMgZhyCI+uicR2Aw==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.1"
    }
}
