{
    "data": "ENC[AES256_GCM,data:p/MDrAi/ZTWlolpGTWhp6wpbauJ0RxvAa8raAoPEtuu1MJaYQAIzUC1PpGnbOqQ8fMN7dADZ/qdMGTQWUJNp7b0Ers03w83+Wx/pcEZNqe3aih9jUitGrDdSisGU+tmR5rKRHPewJDMMw/+ycBt10z/AlODKqQpT6ivAvxqTrAlOi1hmeZjSf63BKRbk9jFUqYYOLz2XRfcq/nweRF9+yPREWGmO5LOiRICdEtKVoXIoWpCykUN9VRwpJB+mLSHX3t2hayeK1NDqYK7ik6qdRLSWiNHjSSHLhWhVPNUowafeF1xz7phqGg==,iv:xi3O2oaK11kyWLS8OMtURpQMrRv4Txkwx6djhVj5hXE=,tag:PsFsL+WoNLippjRStK66Rg==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TXYyZ0hSZHA3TGF0U0R3\nMU1Xc2tjWklsMFFISUNpRGZqUTNOL0t1dlRBCmFuSUZWY0lWd0d5a240RFRYSERT\nRE13SGJyanJQYm5OTWdhYk15M1hBdHcKLS0tIGhlNnZ3cVJGQTE5YkRCZm1WWmts\nTlhibUZHbkx0bDhqOXBocTE0b0tlQlUKvKY1uW2kKA1zqhizCWKgCxBeBZGAwFXF\nOhQMiDHto3XFSW00oqjlE0w4CVdJwwv82pe22Kzw0tYS4lQq0O4J6w==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-08-14T21:43:32Z",
        "mac": "ENC[AES256_GCM,data:84OELWpxA9ffrWi8hbn3+Hm/IkmB/WwZ81wY0BWH5S0F+LHbOcQIKTujmO3/vTYUP7oPprjRG+NIxm3pqlR+VqSZPHdX67aXqu8p+1oUTInxXxl1nSGKqiE+TYvPnVGBREaXwTvNZ2zELQ2kAD4pAxlW41L/nSNcQXXhjUJ6qUc=,iv:IElFZOvcDE4fmESz1PDN+w5AxjefDF7/EStLCJ0wN10=,tag:yFbvVBOScNA0AuyclS9ohQ==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.1"
    }
}
