{
    "data": "ENC[AES256_GCM,data:zGaaEjY2YeYJ0v46TGXQl0bXR8zTrcj0DBMVKJuPuXUxbMMzgr0+jixwVE69blD8hPk3Xpd9hb8v1W3gh88OS0BVJq4n5NYQNK4qq0di0s7Pf3f33le7sF9NRDD4gUZZmbhr+jadZmbn82QSabNLI3+8aMoDBYtVEgounkG5MfE10hD0R2gWzvneeAv4nxjQrTp/Nb/oMuSu17446a90aut0b0snq6SGzp5SVctGMYpS+7N+ReUP7Gb4H9bdJYDiEOnLMUD8t/xvFBHGRrcxExyVaw+goIXoUDoNMP1Fhp4J+g+cSd0eqaB83hY1xwu04b8sTQb7w8TMpztaU9u+nf3M2cMbV2nOuTuc6J6wLoNomuVn28HwzieeI68ZWyGej+OVZZWNycSHxBMfrqhPX4EQW8j2uy1lk/GWlyH938g9cK0q/cMgZD87etMJTVS3u/uFonuWR1R0DP331hDhQ1lJloqNBe1uVPDwA2OdktAGUHHCw0uikbg16dtqzMJwL2YCGerd8Maj3Gn9M2JzxKlJrqMG/v2w1fn3w1Ib1IihhNw7nenMoqpTlrVrJIZ2GaB6qyPXNGR8m+F6mMl92H3fipchm/z8pUM06T4X+QgxwZdNCa7bqDW31ek1ny0m9xfEvcimmH7lmwVCwuGyHwhqga+0IsmReK5GWHIa/Jn+nLMOgQlcLNXQIFoQPcEnLSNcV1Rf/4YzMeNf8use1GG6XX3V+/Vyb2TDmNRfY1hMDzPLQiH8DEBjEzUJTpUPLu9TO/f+3mZ4X9uWVj1MSz0nDDYumv1hhv+ufQJRrPlpaSdrIM87WfGhRcVe8g80u1eQ/ipwc4Jy2cgIUNNOemauLI/ISykcli1aQFqXX6iSK5COg/YU0ckLG8nNve4heumtbyesPv2FUkc4+9YeA8jV8hy4JEqtiO9PwhtM7tjkPnxpvv5yXugnfbp38IJo+oJnwr0GxKYtXI1qYF36TCnF+Vy+1OwVTK2qI2x5V1iKfl2f+SHeK83TwrM3ZZZqiUnSKbWEj1NVO/7IlImm2NSomH8bKZWTIfNjD7A/tjpbyz5ZK/RGWuCDbHOd54bw1S2A1ngRLAK8xWC0lTuATgUmvpU64VknBvYdBXaVdXHXbuqtIse0v9ZG1uTBdQGWMCoYSIEXdf7msYffP/CST0EIgGPdoNEZbnwcyTsxoiNOwVnEDhmTq6JWgLjvlrTtGxLy3MnwHhtcjwiEnEeK,iv:e6loNmsgBJryTLoAu03jHemKPVn/XGgprcNM2MPBKnI=,tag:GN/L+5Jh+Z3rkGPOUgo3eA==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VVpCMGNMeDlOWWZ5Qk42\nc0dlZCtZZ3pRNXdwWVNPYWhYbzVOQm50MVhZCklrTTl2V0ppZTJKdzhPUk9NQy9W\nQVlRTEhLdkhjWmY4Qlg2NVQwcDNHQmcKLS0tIG8rYUtJaFpFblcwalVjNFJDb051\nVGxkMmlmclpUdVU1cXluck93Z2dsS0UKng5dSIGG2zq7K8I+VMrbvft7ReNzJTiz\nb3mTRigzMqj+6qGC/Ibo+/4tFaIdm6j1haEMb39aB/9mUpX9FTXxKw==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-08-14T16:02:32Z",
        "mac": "ENC[AES256_GCM,data:IFAWr2FMlW41DmO/ZjOX1SCYI5+o6Rd4XymYshtFlOqOF5s4RiAkcZ4wGEfF8quD836QD3XOKL3yeA4/anmN85Z0q2zl1uVRLdm1/X4/PdRjnPO6VTBAHmmMQ72CKvNclluJNy4txcz4UepYEnNz/8cDby2FgpUJiFpvtvsAS5g=,iv:rFE53G4T1dnjHRZhYu7RAjIZHJq/pnNFQik5umq6cIA=,tag:K63ZGL+aDJgY6iw4dJwyWg==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.1"
    }
}
