{
    "data": "ENC[AES256_GCM,data:jf+Q1oaWSfhF9pxuiIdUgQZvknyzRKaYyOM3yFhBeABf+Hl8XZx9BLf+W8JWeL9+pyWHq5mLOQejpiEhI4w9c+Gjby5KtxmC50QXhMijE80TC8gIPv08zP3Ua3HzttGNNqf1/BPhnc/9QC5S59YulYkq1l0Sl25c97BfJsBPhlp2Qab9AuT0vX1zx+sYeKHxLbvK7mkZaamG00uViMH/zshtqzrRtcsRfTM/Z+UmFHKmuHJKZ1G5Yv1C28CqEaItQU815AyOgedqW5kM+uT+iyjYxkcuvO6P49spjjEyQo0ndqXq/9ylJY27Ai0adGSxOSPl75ZqY9YmFKC8FsxnuTePpPn7VzIiP56jtVk7aNRYAOdnpSeSyycHoAWz14TrxGRp9wAvTHZpMtDmJBbo2XVTsusMCKIru1lqecmhvvCrumEepCUWrR0xUDaCg+Hqov1TyZ+k14Ic1rybah3Aim/t4jUk7THFNZz1KYKSwPZulGXR0y0dFaGTpE60LrjCIftjGdk2Bora2xocFU8ynqQUMb09d+521NLroQLXhI734/leImNMU77foOvZ1LLrAP5tyYe/eyCdsNpncItCUa4CL5Nw2Aeo0Y9RWGs0MhOP/hGswyZleOWbPK86Xq7Dolx+6uN6DdttHMVW32XJG2W1mHod3vYXB1rbS/qcdgpAbEodumrh3wS1+eaoDkEBoRXeJoStwTtxRNkx7AEyFUbvoemvndfiJcwWbQJ7IWpanAxI2xeOo1poWABU7NxuHlfmWKNspaCtYWa3Fg4yhP0wrdVfsEqlC24Y8yi33Wu/+3U/hJ80iY4kDI+rAHVpUKyXn487w87Ut0k+NNXoj5qUe524XOnP6dlJApjpsAWb2JKiX54XMWt7S7X5MBDBq3VxsUmvYLDkIBMiWYm5OWm9Dd5aM9Y5Qt2EfF8gzY5vx7xu3XHIOrTFpMZI0aZnBcLDrGMpe1qiKeO2RhimSB7mg9M9X/roqJf0qplgDQpiJaeA/LSLnwphuCQuzt+438fR0rUoxOgzyqIXmwBwjS8Hl2rrX46cMsFXvFcb42HsBEGKX3H2ELlo30Er+f2cdm1eJreTBHi6bznYMMgGZFDpV7vdP7Q9q/+Mu/8o0Q150um2i4XaiBLnomwWU35iQ+Nd0mpqn0Y6ViVuU6daEXMvSWc9p1Qvtw2xQDz/u/KVhsT7JYWzHsbM7jWpRs6D0ACCI3WjHVxuBeydkKmP,iv:TQKFT7Z7MKAioL8JsIE5yu2j0H+PNQvEJQVgkkA6q98=,tag:PnQMdPBabsvNkopd1R/xgQ==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1rhy2neq0qg7y6svfu2pcyd85z3wkgspkgzz4jcmguypymk3e958qzhgwqx",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VVpCMGNMeDlOWWZ5Qk42\nc0dlZCtZZ3pRNXdwWVNPYWhYbzVOQm50MVhZCklrTTl2V0ppZTJKdzhPUk9NQy9W\nQVlRTEhLdkhjWmY4Qlg2NVQwcDNHQmcKLS0tIG8rYUtJaFpFblcwalVjNFJDb051\nVGxkMmlmclpUdVU1cXluck93Z2dsS0UKng5dSIGG2zq7K8I+VMrbvft7ReNzJTiz\nb3mTRigzMqj+6qGC/Ibo+/4tFaIdm6j1haEMb39aB/9mUpX9FTXxKw==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-08-15T12:59:28Z",
        "mac": "ENC[AES256_GCM,data:KBjM8a0Y0U+qWaifgU9ZiITFqYfoTdpbRxxu4JhDHzZEBLvDw3CUTW1YHL25YbS0ngwJBt/5EX6GwcdfhS/NLHKIgZyJ4xgg/srbQpXEvFo/1NKuaZ3Da2h/qYJEZorQvvb6MYevax3uIbBZ4PLHWuSLWotZn5AYVEaCiKudwT4=,iv:Y+/AkrQEh/VnAIR42wwFmAQc7GngOmjApEHGYiEMd2Q=,tag:6RAgOyTwWWv+FercXBYHsA==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.1"
    }
}
