---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: transmission
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
      TRANSMISSION_RPC_PASSWORD: "transmission2145"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: transmission.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - transmission.sparks.codes
            secretName: acme-crt-secret-sparks-codes
      persistence:
        downloads:
          enabled: true
          storageClass: ceph-block
          accessMode: ReadWriteMany
          size: 25Gi
