---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: transmission
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Chicago"
      TTRSS_SELF_URL_PATH: https://rss.sparks.codes/
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: rss.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - rss.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    postgresql:
      persistence:
        enabled: true
