---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: focalboard
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: focalboard
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      FOCALBOARD_PORT: 8000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-internal
          hajimari.io/enable: "true"
          hajimari.io/appName: "Focalboard"
          hajimari.io/icon: "bulletin-board"
        hosts:
          - host: boards.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - boards.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      data:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 10Gi
        retain: true
