---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-ha
  namespace: lan-services
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10gbe-tango.sparks.codes
    path: "/mnt/local/storage/k8s-nfs/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-ha
  namespace: lan-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
