---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-lan-services
  namespace: lan-services
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: omega.sparks.codes
    path: "/mnt/static"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-lan-services
  namespace: lan-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
