---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    speaker:
      frr:
        enabled: true
      tolerations:
        - key: dns-master
          operator: Equal
          value: "active"
          effect: NoSchedule
        - key: iot-master
          operator: Equal
          value: "active"
          effect: NoSchedule
