---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    controller:
      image:
        repository: metallb/controller
        tag: main
    speaker:
      image:
        repository: metallb/speaker
        tag: main
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          auto-assign: true
          addresses:
            - 10.10.200.0/24
        - name: services
          protocol: layer2
          auto-assign: false
          addresses:
            - 10.10.201.0/24
        - name: minecraft
          protocol: layer2
          auto-assign: false
          addresses:
            - 10.10.202.0/24
