---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app emqx
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    env:
      TZ: "America/Chicago"
    replicaCount: 3
    recreatePods: true
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
    service:
      type: LoadBalancer
      externalIPs:
        - "10.10.201.3"
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx-internal
        path: /
        pathType: Prefix
        hosts:
          - &host "emqx.sparks.codes"
        tls:
          - hosts:
              - *host
    metrics:
      enabled: false
    persistence:
      enabled: true
      existingClaim: emqx-data-pvc
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - rpi4-poe-1
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 10m
        memory: 150Mi
      limits:
        memory: 512Mi
    tolerations:
      - key: iot-master
        operator: Equal
        value: "active"
        effect: NoSchedule
  valuesFrom:
    - targetPath: emqxConfig.EMQX_ADMIN_PASSWORD
      kind: Secret
      name: emqx-config
      valuesKey: admin_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-config
      valuesKey: user_1_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-config
      valuesKey: user_1_password
