---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/mqtt.sparks.codes/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rpi4-poe-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data-pvc
  namespace: home
spec:
  volumeName: emqx-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Mi
