apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-dns
  - metallb
  - multus
  - nginx-ingress
  - reflector
  - sources
  - storage
  - system-upgrade
