---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: stash
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/Chicago"
    node-selector: omega
    persistence:
      config:
        enabled: true
        mountPath: /root/.stash
        existingClaim: stash-config-pvc
        accessMode: "ReadWriteOnce"
        size: 1Gi
      metadata:
        enabled: true
        mountPath: /metadata
        existingClaim: stash-metadata-pvc
        accessMode: "ReadWriteOnce"
        size: 25Gi
      media:
        enabled: true
        mountPath: /media
        existingClaim: stash-data-pvc
        accessMode: "ReadWriteOnce"
        size: 200Gi
      cache:
        enabled: true
        mountPath: /cache
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 10Gi
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
          hajimari.io/enable: "false"
        hosts:
          - host: stash.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - stash.sparks.codes
            secretName: acme-crt-secret-sparks-codes
