---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/static/stash.sparks.codes/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-data-pvc
  namespace: media
spec:
  volumeName: stash-data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
