---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: statping
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: statping
      version: 5.7.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/Chicago"
      VIRTUAL_HOST: uptime.sparks.codes
      NAME: "Spark's Uptime Report"
      ADMIN_USER: sparks
      ADMIN_PASSWORD: choosesomethingelse@
      ADMIN_EMAIL: uptime@sparks.codes
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Statping"
          hajimari.io/icon: "gauge"
        hosts:
          - host: uptime.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - uptime.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    persistence:
      data:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 1Gi
    postgresql:
      enabled: true
      postgresqlPassword: choosesomethingelse
      persistence:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 8Gi
