---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/nginx-ingress
      chart: ingress-nginx
      version: 3.35.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      admissionWebhooks:
        enabled: false
      replicaCount: 1
      config:
        use-proxy-protocol: false
        force-ssl-redirect: "false"
      use-forwarded-headers: "true"
      service:
        loadBalancerIP: 10.11.0.1
        externalTrafficPolicy: Local
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret-imake-software"
      resources:
        requests:
          memory: 6Gi
          cpu: 400m
        limits:
          memory: 6Gi
      autoscaling:
        enabled: true
        maxReplicas: 4
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi
