---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 7.6.19
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    publishService:
      enabled: true
    service:
      loadBalancerIP: 10.11.0.1
      externalTrafficPolicy: Cluster
    extraArgs:
      default-ssl-certificate: "cert-manager/acme-crt-secret-imake-software"
    resources:
      requests:
        memory: 1i
        cpu: 200m
      limits:
        cpu: 400m
        memory: 2Gi
    autoscaling:
      enabled: true
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
    tcp:
      "22": "gitlab/gitlab-gitlab-shell:22"
