---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: openldap-stack-ha
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: openldap-charts
        namespace: flux-system
      interval: 15m
  values:
    global:
      ldapDomain: ${TOOLS_OPENLDAP_LDAP_DOMAIN}
      adminPassword: ${TOOLS_OPENLDAP_ADMIN_PASSWORD}
      configPassword: ${TOOLS_OPENLDAP_CONFIG_PASSWORD}
    service:
      type: LoadBalancer
      loadBalancerIP: 10.10.201.7
    phpldapadmin:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-internal
          hajimari.io/enable: "true"
          hajimari.io/appName: "LDAP"
          hajimari.io/icon: "key"
        path: /
        hosts:
          - ldap-admin.sparks.codes
    persistence:
      enabled: false
      storageClass: "ceph-filesystem"
      accessMode: "ReadWriteMany"
