---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: America/Chicago
      GUAC_USER: calibre
      GUAC_PASS: "${MEDIA_CALIBRE_GUAC_PASSWORD}"
    image:
      tag: latest
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
          nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          hajimari.io/enable: "false"
        hosts:
          - host: "books-backend.sparks.codes"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "books-backend.sparks.codes"
            secretName: acme-crt-secret-sparks.codes
    persistence:
      config:
        enabled: true
        existingClaim: local-calibre-config
      books:
        enabled: true
        existingClaim: local-calibre-books
