---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homekit-bridge
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: oznu/homebridge
      tag: 'latest'
    env:
      TZ: "America/Chicago"
    node-selector: omega
    persistence:
      config:
        enabled: true
        existingClaim: homekit-bridge-pvc
        mountPath: /homebridge
        accessMode: "ReadWriteOnce"
        size: 2Gi
    service:
      main:
        ports:
          http:
            port: 8581
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Homekit Bridge"
          hajimari.io/icon: "apple-finder"
        hosts:
          - host: bridge-homekit.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - secretName: acme-crt-secret-sparks-codes
            hosts:
              - bridge-homekit.sparks.codes
    dnsConfig:
      options:
        - name: ndots
          value: "1"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
