---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homekit-bridge-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ceph-block"
  resources:
    requests:
      storage: 2Gi
