---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool-lng-whiskey
  namespace: openebs
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 4Gi
      - name: PoolResourceLimits
        value: |-
            memory: 8Gi
spec:
  name: cstor-disk-pool-lng-whiskey
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList: []

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-disk-lng-whiskey
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk-pool-lng-whiskey"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Retain
