---
kind: Service
apiVersion: v1
metadata:
  name: external-sprk-sh
  namespace: tools
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sprk.sh
spec:
  type: ExternalName
  externalName: sprk.sh
