---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: shlink
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: shlink
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/Chicago"
      SHORT_DOMAIN_HOST: "sprk.sh/go"
      SHORT_DOMAIN_SCHEMA: "https"
      # GEOLITE_LICENSE_KEY: "kjh23ljkbndskj345"

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Shlink"
          hajimari.io/icon: "link"
        hosts:
          - host: sprk.sh
            paths:
              - path: "/go"
                pathType: "Prefix"
        tls:
          - hosts:
              - sprk.sh
            secretName: acme-crt-secret-sprk-sh
    persistence:
      params:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 1Gi
      data:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 2Gi
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 2Gi
