---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-imake-software
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
spec:
  secretName: acme-crt-secret-imake-software
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "imake.software"
    - "*.imake.software"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-sparks-codes
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "networking,home,games,kube-system,media,gitlab,nginx,rook-ceph"
spec:
  secretName: acme-crt-secret-sparks-codes
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "sparks.codes"
    - "*.sparks.codes"
