---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-imake-software
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "nginx,home,default,kube-system,flux-system,games,gitlab,kube-public,media,networking,rook-ceph"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "nginx,home,default,kube-system,flux-system,games,gitlab,kube-public,media,networking,rook-ceph"
  secretName: acme-crt-secret-imake-software
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "imake.software"
    - "*.imake.software"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-sparks-codes
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "nginx,home,default,kube-system,flux-system,games,gitlab,kube-public,media,networking,rook-ceph"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "nginx,home,default,kube-system,flux-system,games,gitlab,kube-public,media,networking,rook-ceph"
  secretName: acme-crt-secret-sparks-codes
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "sparks.codes"
    - "*.sparks.codes"
