apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: velero-bucket
  namespace: rook-ceph
spec:
  bucketName: velero-backups
  # generateBucketName: photo-booth [4]
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "250000"
    maxSize: "2T"
