---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-youtubedl-config
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/static/media.sparks.codes/youtube-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omega

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-youtubedl-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
