apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-operator
  namespace: flux-system
spec:
  interval: 15m0s
  dependsOn:
    - name: rook-ceph-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/core/storage/rook-ceph/rook-operator
  prune: true
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-cluster
  namespace: flux-system
spec:
  interval: 15m0s
  dependsOn:
    - name: rook-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/core/storage/rook-ceph/rook-cluster
  prune: true
  validation: client
