---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-imake-software
  namespace: cert-manager
spec:
  secretName: acme-crt-secret-imake-software
  commonName: "*.imake.software"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.imake.software"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-sparks-codes
  namespace: cert-manager
spec:
  secretName: acme-crt-secret-sparks-codes
  commonName: "*.sparks.codes"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.sparks.codes"
