---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-data-sparks-codes
  namespace: nginx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: nginx
      version: 9.5.11
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    extraVolumeMounts:
      - mountPath: "/app"
        subPath: "data.sparks.codes"
        name: nfsvol
    extraVolumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: nfs-nginx
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx-external"
        ingress.kubernetes.io/force-ssl-redirect: "true"
      hostname: "data.sparks.codes"
      extraTls:
        - hosts:
            - data.sparks.codes
          secretName: acme-crt-secret-sparks-codes
