---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: auth
spec:
  interval: 15m
  chart:
    spec:
      chart: common
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-libraries-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    # - name: postgres
    #   namespace: default
    - name: glauth
      namespace: auth
    # - name: redis
    #   namespace: default
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.36.4
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            enabled: true
            primary: true
            protocol: HTTP
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx-internal"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
        hosts:
          - host: &host "auth.sparks.codes"
            paths:
              - path: /
                pathType: Prefix
                service: http
                backend:
                  servicePort: 80
        tls:
          - secretName: acme-crt-secret-sparks-codes
            hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: configuration.yml
        mountPath: /config/configuration.yml
        readOnly: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 250Mi
