---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: archivebox
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: archivebox/archivebox
      tag: 'latest'
    env:
      TZ: "America/Chicago"
      ALLOWED_HOSTS: '*'
      MEDIA_MAX_SIZE: 750m
    persistence:
      config:
        enabled: true
        existingClaim: archivebox-data-pvc
        mountPath: /data
        accessMode: "ReadWriteMany"
        size: 60Gi
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-internal"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Archivebox"
          hajimari.io/icon: "archive"
        hosts:
          - host: archivebox.sparks.codes
            paths:
              - path: "/"
                pathType: "Prefix"
        tls:
          - hosts:
              - archivebox.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
