---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archivebox-data-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "ceph-filesystem"
  resources:
    requests:
      storage: 60Gi
