---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.8.7
      sourceRef:
        kind: HelmRepository
        name: rook-charts
        namespace: flux-system
      interval: 15m
  values:
    monitoring:
      enabled: false
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: nginx-internal
          hajimari.io/enable: "true"
          hajimari.io/appName: "Rook"
          hajimari.io/icon: "database"
        host:
          name: rook.sparks.codes
          path: "/"
        tls:
          - hosts:
              - rook.sparks.codes
            secretName: acme-crt-secret-sparks-codes
    toolbox:
      enabled: true
    cephClusterSpec:
      dashboard:
        enabled: true
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          metadataDevice:
          osdsPerDevice: "1"
        nodes:
          - name: whiskey
            devices:
              - name: /dev/disk/by-id/lvm-pv-uuid-56ajOl-XAWN-lb2B-9Qrf-1QlX-XDdg-1bzaMr
              - name: /dev/disk/by-id/lvm-pv-uuid-l89iwC-m8gB-udJ7-20fa-FaOx-fj6e-ji482A
              - name: /dev/disk/by-id/lvm-pv-uuid-cZGGe4-Lr10-cl71-b0qJ-Vk4k-78we-sqYqe3
              - name: /dev/disk/by-id/lvm-pv-uuid-LUC2lQ-pvGw-uWdv-CeRH-2JYI-mRQf-h8p3Pv
              - name: /dev/disk/by-id/lvm-pv-uuid-buIHbt-mCqs-U0zm-leiV-5OMS-LLTu-cg1rRB
              - name: /dev/disk/by-id/lvm-pv-uuid-03uX53-8dTO-Xt3r-bpei-x74R-I44H-sj0m5V
          #- name: foxtrot
          #  devices:
          #    - name: sdb
          #    - name: sdc
          #    - name: sdd
          #    - name: sde
          #    - name: sdf
          #    - name: sdg
          #- name: lambda
          #  devices:
          #    - name: sdb
          - name: omega
            devices:
              - name: /dev/disk/by-id/scsi-36c81f660e209af0024db2ede06115d1d-part1
          - name: tango
            devices:
              - name: /dev/disk/by-id/lvm-pv-uuid-ffWw2I-pZxz-3g1Y-tGSK-0HBA-2V0U-ReDTdg
              - name: /dev/disk/by-id/lvm-pv-uuid-8psYbs-uji9-0q2m-KMX3-EEc2-PvHd-qBU81t
              - name: /dev/disk/by-id/lvm-pv-uuid-JR93nM-z71I-SNj7-TN3p-y6Co-AQio-MLU6Pr
              - name: /dev/disk/by-id/lvm-pv-uuid-4y5RG2-SPQz-qMOy-LkYD-BJdl-NGQ6-J6xO8G
              - name: /dev/disk/by-id/lvm-pv-uuid-tfWcBD-Zhho-vJv0-Egu6-lUJ4-KS7N-IxIZmG
              - name: /dev/disk/by-id/lvm-pv-uuid-T97Vca-92Bb-2pRJ-4p7Q-kzP9-9lFC-aylDOl
              - name: /dev/disk/by-id/lvm-pv-uuid-zSRDY3-lu48-hpJx-JCcB-3rw6-GJWy-Z6Epod
              - name: /dev/disk/by-id/lvm-pv-uuid-ZtT2OT-CkWv-hprZ-YBH9-7jfe-oJOx-lCXuRj

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          name: ceph-block
          enabled: true
          isDefault: false
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          # see https://github.com/rook/rook/blob/master/Documentation/ceph-block.md#provision-storage for available configuration
          parameters:
            # (optional) mapOptions is a comma-separated list of map options.
            # For krbd options refer
            # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
            # For nbd options refer
            # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
            # mapOptions: lock_on_read,queue_depth=1024

            # (optional) unmapOptions is a comma-separated list of unmap options.
            # For krbd options refer
            # https://docs.ceph.com/docs/master/man/8/rbd/#kernel-rbd-krbd-options
            # For nbd options refer
            # https://docs.ceph.com/docs/master/man/8/rbd-nbd/#options
            # unmapOptions: force

            # RBD image format. Defaults to "2".
            imageFormat: "2"
            # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
            imageFeatures: layering
            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            # Specify the filesystem type of the volume. If not specified, csi-provisioner
            # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
            # in hyperconverged settings where the volume is mounted on the same node as the osds.
            csi.storage.k8s.io/fstype: ext4

    cephFileSystems:
      - name: ceph-filesystem
        # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem-crd.md#filesystem-settings for available configuration
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
          metadataServer:
            activeCount: 1
            activeStandby: true
        storageClass:
          enabled: true
          isDefault: true
          name: ceph-filesystem
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          # see https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#provision-storage for available configuration
          parameters:
            # The secrets contain Ceph admin credentials.
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            # Specify the filesystem type of the volume. If not specified, csi-provisioner
            # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
            # in hyperconverged settings where the volume is mounted on the same node as the osds.
            csi.storage.k8s.io/fstype: ext4

    cephObjectStores:
      - name: ceph-objectstore
        # see https://github.com/rook/rook/blob/master/Documentation/ceph-object-store-crd.md#object-store-settings for available configuration
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            # securePort: 443
            # sslCertificateRef:
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Retain
          # see https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#storageclass for available configuration
          parameters:
            # note: objectStoreNamespace and objectStoreName are configured by the chart
            region: us-east-1
