---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
      interval: 5m
  values:
    gitlabUrl: https://gitlab.imake.software/
    runnerRegistrationToken: qfmrRodyMsymGaZrvS_s
    replicas: 2
    rbac:
      create: true
