---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 5.4.15
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    provider: cloudflare
    policy: upsert-only
    cloudflare:
      email: sparksd2145@gmail.com
      secretName: cloudflare-credentials-externaldns
      proxied: false
    sources:
      - service
    serviceTypeFilter:
      - ExternalName
    domainFilters:
      - imake.software
      - sparks.codes
    txtPrefix: sparks-txt-
