---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nvidia-gpu-operator
      version: v1.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    operator:
      defaultRuntime: containerd
    nfd:
      enabled: false
